export default [
    {
        id: 1,
        name: "Ivan Dnepropetrivisk",
        username: "dnepro",
        website: "",
        bio: "Shit!",
        email: "ivan@gmail.com",
        number: "0506596859",
        gender: true,
    },
    {
        id: 2,
        name: "Romeo Korey",
        username: "koreyroameo",
        website: "romeokorey.net",
        bio: "Nice dick bro!",
        email: "korey@gmail.com",
        number: "0504596859",
        gender: true,
    },
    {
        id: 3,
        name: "Sonia Gucci",
        username: "gucc",
        website: "gucci.com",
        bio: "eeiuhjegbvr!",
        email: "sonya@gmail.com",
        number: "0506546859",
        gender: false,
    },
    {
        id: 4,
        name: "M7emmad",
        username: "7emmad",
        website: "5ara.net",
        bio: "okololol!",
        email: "7amad@gmail.com",
        number: "0506596856",
        gender: true,
    },
    {
        id: 5,
        name: "Khadija Johnson",
        username: "5adej",
        website: "m7md.net",
        bio: "rgterhntrf",
        email: "lol@gmail.com",
        number: "0506595539",
        gender: false,
    },
];
